import { Service } from "./types";

export const SAMPLE_SERVICES: Service[] = [
  {
    id: "ncda",
    name: "NCDA",
    description:
      "The National Council on Disability Affairs (NCDA) is the government agency mandated to formulate policies and coordinate the activities of all agencies concerning disability issues and concerns.",
    websiteLink: "https://www.ncda.gov.ph",
    imageKey: "ncda",
    image: require("@/assets/images/services/ncda.png"),
    shortcuts: [
      {
        id: "ncda1",
        name: "PWD ID Application",
        description: "Apply for Person with Disability Identification Card",
        icon: "person.crop.circle.badge.checkmark",
        androidIcon: 'id-card',
        gradientStart: "#FF6B6B",
        gradientEnd: "#FF8E8E",
        serviceName: "NCDA",
        steps: [],
      },
      {
        id: "ncda2",
        name: "Disability Certification",
        description: "Request for disability certification and assessment",
        icon: "doc.text.fill",
        androidIcon: 'document-text',
        gradientStart: "#4ECDC4",
        gradientEnd: "#45B7AC",
        serviceName: "NCDA",
        steps: [],
      },
      {
        id: "ncda3",
        name: "Assistive Device Support",
        description: "Apply for assistive technology devices",
        icon: "accessibility",
        androidIcon: "accessibility",
        gradientStart: "#96CEB4",
        gradientEnd: "#7AB59B",
        serviceName: "NCDA",
        steps: [],
      },
      {
        id: "ncda4",
        name: "Employment Assistance",
        description: "Access employment opportunities for PWDs",
        icon: "briefcase.fill",
        androidIcon: "briefcase",
        gradientStart: "#FF9F9F",
        gradientEnd: "#FF8787",
        serviceName: "NCDA",
        steps: [],
      },
      {
        id: "ncda5",
        name: "Disability Benefits",
        description: "Learn about available benefits and programs",
        icon: "heart.fill",
        androidIcon: "heart",
        gradientStart: "#88D8B0",
        gradientEnd: "#6FC49A",
        serviceName: "NCDA",
        steps: [],
      },
    ],
  },
  {
    id: "doh",
    name: "DOH",
    description:
      "The Department of Health (DOH) is the principal health agency in the Philippines responsible for ensuring access to basic public health services by all Filipinos.",
    websiteLink: "https://doh.gov.ph",
    imageKey: "doh",
    image: require("@/assets/images/services/doh.png"),
    shortcuts: [
      {
        id: "doh1",
        name: "Vaccination Schedule",
        description: "Check and schedule vaccination appointments",
        icon: "syringe",
        androidIcon: "calendar",
        gradientStart: "#6C63FF",
        gradientEnd: "#574FCC",
        serviceName: "DOH",
        steps: [],
      },
      {
        id: "doh2",
        name: "Medical Assistance",
        description: "Apply for medical financial assistance",
        icon: "cross.case.fill",
        androidIcon: "medical",
        gradientStart: "#FF6B6B",
        gradientEnd: "#FF8E8E",
        serviceName: "DOH",
        steps: [],
      },
      {
        id: "doh3",
        name: "Health Facility Finder",
        description: "Locate nearest health facilities",
        icon: "building.2.fill",
        androidIcon: "search",
        gradientStart: "#4ECDC4",
        gradientEnd: "#45B7AC",
        serviceName: "DOH",
        steps: [],
      },
      {
        id: "doh4",
        name: "Drug Price Inquiry",
        description: "Check medication prices and availability",
        icon: "pills.fill",
        androidIcon: "pricetag",
        gradientStart: "#FFD93D",
        gradientEnd: "#FFB302",
        serviceName: "DOH",
        steps: [],
      },
      {
        id: "doh5",
        name: "COVID-19 Updates",
        description: "Get latest COVID-19 information and guidelines",
        icon: "waveform.path.ecg",
        androidIcon: "newspaper",
        gradientStart: "#FF9F9F",
        gradientEnd: "#FF8787",
        serviceName: "DOH",
        steps: [],
      },
    ],
  },
  {
    id: "dswd",
    name: "DSWD",
    description:
      "The Department of Social Welfare and Development (DSWD) is the primary government agency mandated to develop, implement and coordinate social protection and poverty-reduction solutions for and with the poor, vulnerable and disadvantaged.",
    websiteLink: "https://www.dswd.gov.ph",
    imageKey: "dswd",
    image: require("@/assets/images/services/dswd.png"),
    shortcuts: [
      {
        id: "dswd1",
        name: "4Ps Registration",
        description: "Register for Pantawid Pamilyang Pilipino Program",
        icon: "person.3.fill",
        androidIcon: "pencil",
        gradientStart: "#6C63FF",
        gradientEnd: "#574FCC",
        serviceName: "DSWD",
        steps: [],
      },
      {
        id: "dswd2",
        name: "Social Pension",
        description: "Apply for senior citizen social pension",
        icon: "banknote.fill",
        androidIcon: "cash",
        gradientStart: "#4ECDC4",
        gradientEnd: "#45B7AC",
        serviceName: "DSWD",
        steps: [],
      },
      {
        id: "dswd3",
        name: "Food Aid",
        description: "Request food assistance program",
        icon: "cart.fill",
        androidIcon: "cart",
        gradientStart: "#FFD93D",
        gradientEnd: "#FFB302",
        serviceName: "DSWD",
        steps: [],
      },
      {
        id: "dswd4",
        name: "Crisis Intervention",
        description: "Get help during crisis situations",
        icon: "exclamationmark.triangle.fill",
        androidIcon: "warning",
        gradientStart: "#FF6B6B",
        gradientEnd: "#FF8E8E",
        serviceName: "DSWD",
        steps: [],
      },
      {
        id: "dswd5",
        name: "Child Welfare",
        description: "Access child protection services",
        icon: "figure.child.circle",
        androidIcon: "happy",
        gradientStart: "#88D8B0",
        gradientEnd: "#6FC49A",
        serviceName: "DSWD",
        steps: [],
      },
    ],
  },
  {
    id: "dict",
    name: "DICT",
    description:
      "The Department of Information and Communications Technology (DICT) is the executive department responsible for the planning, development, and promotion of the country's ICT agenda.",
    websiteLink: "https://dict.gov.ph",
    imageKey: "dict",
    image: require("@/assets/images/services/dict.png"),
    shortcuts: [
      {
        id: "dict1",
        name: "Free WiFi Access",
        description: "Register for free public WiFi service",
        icon: "wifi",
        androidIcon: "wifi",
        gradientStart: "#6C63FF",
        gradientEnd: "#574FCC",
        serviceName: "DICT",
        steps: [],
      },
      {
        id: "dict2",
        name: "Digital Skills",
        description: "Access free digital literacy training",
        icon: "graduationcap.fill",
        androidIcon: "desktop",
        gradientStart: "#4ECDC4",
        gradientEnd: "#45B7AC",
        serviceName: "DICT",
        steps: [],
      },
      {
        id: "dict3",
        name: "Tech4ED Centers",
        description: "Find nearest Tech4ED center location",
        icon: "building.columns.fill",
        androidIcon: "school",
        gradientStart: "#FFD93D",
        gradientEnd: "#FFB302",
        serviceName: "DICT",
        steps: [],
      },
      {
        id: "dict4",
        name: "Cybersecurity",
        description: "Learn about online safety and security",
        icon: "lock.shield.fill",
        androidIcon: "lock-closed",
        gradientStart: "#FF6B6B",
        gradientEnd: "#FF8E8E",
        serviceName: "DICT",
        steps: [],
      },
      {
        id: "dict5",
        name: "E-Government",
        description: "Access various e-government services",
        icon: "network",
        androidIcon: "logo-apple-ar",
        gradientStart: "#88D8B0",
        gradientEnd: "#6FC49A",
        serviceName: "DICT",
        steps: [],
      },
    ],
  },
];
